inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/VariableName:
  EnforcedStyle: snake_case

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120
  AllowHeredoc: enabled
  AllowURI: enabled
  Exclude:
    - 'spec/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: space

# allow to describe comments with Japanese
Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/MultilineTernaryOperator:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

#
# temporarily disabled cops
#

Style/RedundantArgument:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/HashAlignment:
  EnforcedColonStyle: table

Style/ClassVars:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - e
    - fg
    - bg
    - id
    - ym
    - io

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantLineContinuation:
  Enabled: false

# RSpec cops

RSpec/ContextWording:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/LeakyConstantDeclaration:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
RSpec/VerifiedDoubles:
  Enabled: true
  Exclude:
    - 'spec/lib/receiptisan/model/receipt_computer/digitalized_receipt/parser/processor/si_processor_spec.rb'
RSpec/ExampleLength:
  Max: 10
